### ISSUE TITLE
Link to organisation ID assumes (sometimes incorrectly) it's a publisher

### ISSUE THREAD

**Issue by markbrough** [IATI/D-Portal#642] opened 2022-03-21 11:12 UTC
On this activity:
https://d-portal.org/savi/?aid=GB-GOV-1-300114-103

One of the participating-orgs is the `Ministry of Health - Ethiopia`

<img width="887" alt="image" src="https://user-images.githubusercontent.com/688113/159249318-6cec8158-ef06-43eb-bec8-92fa6ff3fd3b.png">

UK FCDO is already using the government organisation ID methodology [detailed on Gov ID Finder](https://gov-id-finder.codeforiati.org/about/) (nice!).

However, when you click on the ref (`ET-COA-341`), it takes you to the following URL, assuming it's a publisher:
http://d-portal.org/ctrack.html?publisher=ET-COA-341

Whereas this might be a better URL:
https://d-portal.org/ctrack.html?/participating-org@ref=ET-COA-341#view=main

**Comment by notshi** [comment] 2022-03-21 15:45
Thanks for raising, Mark.

This was discussed a bit previously [here](https://github.com/devinit/D-Portal/issues/602).

The SAVi view just displays what it knows about the data on the page, it doesn't do any pre-calculations or lookups. With this suggestion, it needs to know which `participating-org@ref` is not a publisher before it can render the page.

I suppose I could look for `@role` codes 2, 3 and 4 as these are not [funding roles](https://iatistandard.org/en/iati-standard/203/codelists/organisationrole/). Though we are not sure if this is a good way to distinguish them.

We feel that every organisation id in IATI should have an org-file to describe something about the organisation - not just publishers. This would really help give context to the data and as such, give us a place to point to for instances like this.

**Comment by stevieflow** [comment] 2022-03-23 08:29
This one again!

I think this is going to be a more and more common problem, given that @aidtransparency are now pushing major publishers to include an org ref for their participating-org : https://github.com/pwyf/2022-Index-indicator-definitions/issues/25

eg: FCDO have a high number of org references, but not IATI publishers: http://d-portal.org/savi/?aid=GB-1-202643 (about 23k in total: https://datasette.codeforiati.org/iati/participatingorg?_sort=rowid&ref__not=GB-GOV-1&prefix__exact=fcdo&ref__notblank=1)

Hence, this issue won't go away, and it's great that d-port (again) illustrates this.  

Could an initial / interim step be to create the active link to the publisher page when a ref matches a reporting-org:
https://codelists.codeforiati.org/ReportingOrganisation/ ?

> I suppose I could look for @role codes 2, 3 and 4 as these are not [funding roles](https://iatistandard.org/en/iati-standard/203/codelists/organisationrole/).

I dont think that would work - as some publishers will be in these roles

> We feel that every organisation id in IATI should have an org-file to describe something about the organisation - not just publishers. This would really help give context to the data and as such, give us a place to point to for instances like this.

I completely agree - but that's going to take quite a lot of time and energy.  If the *only* place to see the issue is d-portal, and all we do is send people to blank pages, it'll make it harder for advocacy.  Sorry - again, it's not your fault!

**Comment by amy-silcock** [comment] 2022-03-23 15:40
It would be great to find a solution to this. I've also seen it with more UN agencies wanting to publish a ref for participating organisations, and is generally advocated for. 

Potentially as Steven's mentioned, using the Registry API and two step approach.

1) If the org ID is on the Registry, link to the d-portal organisation page
2) If the org ID is not on the Registry, link to the a d-portal page searching for them as a participating organisation?

**Comment by stevieflow** [comment] 2022-03-23 17:26
Thanks @amy-silcock 


Re: 

> If the org ID is not on the Registry, link to the a d-portal page searching for them as a participating organisation?

Looking at this requirement in the above example from @markbrough : 

https://d-portal.org/savi/?aid=GB-GOV-1-300114-103

> 

Ministry of Health - Ethiopia | REF ET-COA-341
-- | --


Ministry of Health - Ethiopia
	
REF [ET-COA-341](https://d-portal.org/ctrack.html?publisher=ET-COA-341)

- [T-COA-341](https://d-portal.org/ctrack.html?publisher=ET-COA-341) is not on the ReportingOrg list: https://codelists.codeforiati.org/ReportingOrganisation/
- Searching for the string "ET-COA-341" would not bring results: https://d-portal.org/ctrack.html#view=search&text_search=ET-COA-341
- Searching for the narrative supplied "Ministry of Health - Ethiopia" does bring something (quite a lot, in fact: https://d-portal.org/ctrack.html#view=search&text_search=Ministry%20of%20Health%20-%20Ethiopia

I *think* the preference might be:

- all activities that have a participating-org/@ref or transaction/provider-org|receiver-org?@ref= "ET-COA-341" - which might be more overhead for d-portal to process....

**Comment by stevieflow** [comment] 2022-03-23 21:40
.. actually - would the search for a non-publisher be:

https://d-portal.org/ctrack.html?/participating-org@ref=ET-COA-341#view=main (thanks @markbrough )?

**Comment by amy-silcock** [comment] 2022-03-24 08:58
That's more what I was thinking @stevieflow :)

**Comment by notshi** [comment] 2022-03-24 11:00
Many thanks, all.

The issue remains that this still means we would need to look up which `participating-org` are publishers before we could render the page. This is not something SAVi does.

As such, we suggest displaying participating-orgs on all publisher pages.
By doing this, non-publisher pages will no longer display blank pages.

Would this be ok, @amy-silcock?

**Comment by amy-silcock** [comment] 2022-03-24 11:09
That could work.

I'd suggest we'd need to alter the design of the page to distinguish between organisation details and participating organisation details. Currently the two page views look really similar and there's a risk of users getting confused between them.

Would be interested to hear thoughts from you all.

**Comment by notshi** [comment] 2022-03-24 11:42
Thanks, @amy-silcock.

The confusion is also probably not helped with the url having the word publisher in it.

When we created d-portal, we were struggling to understand the difference between publisher, organisation, funder, donor, reporting-org, participating-org, provider-org, receiver-org (etc) and with the extremely limited time (3 weeks!!), we had to make a decision and ended up using publisher for all organisation links as that seemed to be the word people kept referring to.

Currently, the obvious (visual) difference between publisher and non-publisher pages on d-portal is the page title; ie. publishers usually have a name displayed which we get from the Registry and non-publisher pages only display their org-ids.

We could add a banner; ie. This organisation id is not listed as a publisher on the IATI Registry - which would be useful to have regardless.

**Comment by stevieflow** [comment] 2022-03-24 12:11
Thanks for the positive discussions on this.  It'll be a great step forward to do something - and appreciate how complex it can be.  Seeing: 

> publisher, organisation, funder, donor, reporting-org, participating-org, provider-org, receiver-org 

.. really illustrates how difficult it can be for someone to engage in IATI!

**Comment by notshi** [comment] 2022-03-26 15:15
Here's a simple mockup of what a participating-org section could look like.

![Screenshot 2022-03-26 at 15-06-04 d-portal](https://user-images.githubusercontent.com/1515961/160245530-925a42e7-9e32-45e9-86af-d3893c42296b.png)

**Comment by stevieflow** [comment] 2022-03-27 08:15
That's really interesting - thanks @notshi 

Obviously, we know that publishers might not get the narrative the same, so this is good to see - given that the org ref aligns.

We haven't really a way to *decide* the name of any org, as there's no authoritative list or protocol --> so I think this is a great first step.  Agree @markbrough @amy-silcock ?

Steps on from this might be to start to declare a name for a participating-org, but that needs wider engagement and support 

Side notes: 

- FindThatCharity by @drkane is very useful in terms of naming orgs that might be on different lists: [A08](https://findthatcharity.uk/

- GrantNav, from @360giving uses official sources to declare the name - here's an example where 20 publishers use the same org reference, but GrantNav uses a single name: https://grantnav.threesixtygiving.org/recipient/GB-CHC-306016 --> @KDuerden might be able to advise.

**Comment by amy-silcock** [comment] 2022-04-26 12:55
This is looking good. To Steven's point, as a first step I'd recommend displaying all publisher names used for participating organisations. As we don't have a way of decided what the 'correct' one is.

Also aware that many organisations will refer to a particular agencies or ministry whilst using a generic reporting org ref/country code. Choosing a name for a non-publisher would seem to be us making too much of a presumption.

**Comment by KDuerden** [comment] 2022-04-27 11:10
thanks @stevieflow

We have the concept of 'canonical name' and 'canonical org id' for Recipient and Funder organisations types
You can see these in the 'additional data' section at the bottom of any grant record.

For example you can see this Comic Relief grant (who I know also publish using IATI Standard): https://grantnav.threesixtygiving.org/grant/360G-CR-4926769

As Steven mentions the canonical name and org ID for recipients is taken from FindthatCharity service for any organisation with an org ID which refers to an official register, and it prioritizes registered charity name and org ID over registered company name, in cases where it's both.

This is why Comic Relief appear with their official registered name when they are a recipient of grants: https://grantnav.threesixtygiving.org/recipient/GB-CHC-326568

When the organisation org ID doesn't refer to an official register the canonical name is the name as shown in the latest grant in the dataset.

For funders the logic is currently different, as it defaults to the Funder name and org ID as per the published data, taking the name from the latest grant.

However it is worth noting that we're in the process of developing GrantNav so that is can merge organisation records (in cases of two different org IDs being published about the same org) and there is some more work to be done to sort out the way it will prioritize names and org IDs.

Our recent discussions trying to sort out priority order logic can be seen here: https://github.com/ThreeSixtyGiving/grantnav/issues/821

**Comment by stevieflow** [comment] 2022-11-17 08:16
I think there are some useful recent updates from 360Giving that might help here @KDuerden ?

**Comment by KDuerden** [comment] 2022-11-18 10:53
thanks @stevieflow. We went live with the update to GrantNav, which includes using a method which tries to link the organisations in 360Giving data, whether they have a role of Publisher, Funder or Recipient in the data.

This uses the Org IDs published in the data, linking together grants when we can, and also data from 360Giving's Data Registry to link Publishers - represented by a 360G-*** prefix - to their known Org ID.

There is a bit more information about how GrantNav is handling organisation data in [our helpsite](https://help.grantnav.threesixtygiving.org/en/latest/organisations.html).

Taking the example of Comic Relief referenced above, this is the new style of consolidated 'org page' in GrantNav: [https://grantnav.threesixtygiving.org/org/GB-CHC-326568](https://grantnav.threesixtygiving.org/org/GB-CHC-326568)

**Comment by notshi** [comment] 2022-11-21 14:05
Thank you @KDuerden for the explanations and notes about this. Appreciate the verbosity and thought behind the processes - it will certainly give us things to think about when we are able to have some development time to work on this.

**Comment by markbrough** [comment] 2024-01-23 17:28
This is fantastic, @notshi!

**Comment by stevieflow** [comment] 2024-01-23 17:57
Woah - great news

**Comment by notshi** [comment] 2024-01-23 20:06
Would this be ok to close, @markbrough?

**Comment by markbrough** [comment] 2024-01-23 20:46
Yep sure from my perspective! Thank you!

**Closed** 2024-01-23 20:51 UTC
Labels: enhancement
