### ISSUE TITLE
No data for FAO

### ISSUE THREAD

**Issue by sarahshamiso** [IATI/D-Portal#603] opened 2021-02-01 16:44 UTC
If you search for FAO under Publisher, there are no results. The files seems to be downloading according the Dashboard so just wondering what the issue might be here?

![image](https://user-images.githubusercontent.com/58748049/106489486-d19a2b80-6482-11eb-8efb-56930ba5e3eb.png)

**Comment by xriss** [comment] 2021-02-02 03:46
HTTPS problems, looks like a badly configured server using ( what are now considered ) insecure keys. You can see the error by trying to fetch the file using curl like so.


```
curl https://sdlc.fao.org/artifactory/fao-iati-releases/Activities.xml

curl: (35) error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small

```

I think we can tweak some settings so that this gets ignored, but it is a problem with the publishers server configuration.

**Comment by sarahshamiso** [comment] 2021-02-03 00:12
Thanks for the explanation! @PetyaKangalova maybe something to flag to FAO?

**Comment by PetyaKangalova** [comment] 2021-02-03 09:34
Thanks all! @amy-silcock  as you emailed FAO last week about validation, can you follow up on your email and flag the server issues as well?

**Comment by notshi** [comment] 2021-02-03 12:56
Just fyi, we have adjusted our end to [ignore curl ssl errors](https://github.com/devinit/D-Portal/commit/555e1744e5e4c9494e3e7c6543ef0c059562d6bc) so FAO should now be filled with data.

**Comment by notshi** [comment] 2021-02-17 13:16
Hello, any updates on this?

**Comment by amy-silcock** [comment] 2021-02-17 14:18
The dev team at FAO have been notified. We sent a 2 week reminder email today asking for an update but haven't heard anything back.

**Comment by notshi** [comment] 2021-02-23 12:19
Thanks, @amy-silcock - hope they respond soon.

**Comment by notshi** [comment] 2021-09-03 12:27
Hi, just wondering if FAO have responded and we can close this?

**Comment by PetyaKangalova** [comment] 2021-09-06 09:47
@notshi  Amy is on leave. I just checked and the latest response we had was back in March that their developers will be addressing the issue, but not a confirmation it  has been done. However, I can see all activities are present on d-portal: http://d-portal.org/ctrack.html#view=search&reporting_ref=XM-DAC-41301

Is there still an issue? If so, I will follow-up.

**Comment by notshi** [comment] 2021-09-06 12:12
Hi @PetyaKangalova, thanks for taking a look at this.

The issue is with the FAO as their server has HTTPS problems where they are using insecure keys.

On our end, we're now ignoring curl ssl errors so we can access their data.

I was under the impression that the issue was kept open to make sure they fixed their end so that other data users will benefit from this fix and to close this issue when that happens.

**Comment by PetyaKangalova** [comment] 2021-09-06 12:57
Hi @notshi ! Okay, I understand now! Let me follow-up with them and get back to you!

**Comment by stevieflow** [comment] 2024-03-06 18:34
This is resolved

https://d-portal.org/ctrack.html#view=search&reporting_ref=XM-DAC-41301 populates 

and

https://iatiregistry.org/publisher/fao does not cite the http error.  There is a separate issue in terms of the file size for FAO, but that does not affect the loading into d-portal

Therefore closing this

**Closed by stevieflow** 2024-03-06 18:34 UTC
Labels: bug, Data
